apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0
VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1ETXdNakUxTWpRd00xb1hEVE16TURJeU56RTFNalF3TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pD
Q0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUh3CnFvS0hncWpCOHFvT3E0eEhCei9aS2pUc3lWUEx1ZnJKNUdKV0N2N1J6OXN0RDRlS1E2NUg3Kz
FwRnhPQ0QrblEKS2JxQnNYTlk4ZHNSWWhzQ1h0QU94czFtRUI3YkpnUGhOaExOeFc2YUFPdHJuVDZVbm1uZVJZaGljeEROTTJXTgo5WUFjWFV1bzZUYWhHYmlKeUJoKzJCbXJi
cWdFRG8rUVFvamQ2MXROdWMvbmdnZVdYUDlCQW5uZ2V4ZkkrR21nCjVMRCtlZ2doWXJuRjdGcjUwSUJ0Mno3blR4SFo1ZEtESmtDdlVDRDJVbTVIK0FvNFU0Ni9YVUdGYmNiYT
hNa3oKclM5dm1tcTY3WWhCS0dhVUdvZDdKcVBnd1dhYU9EeDdIRkp6blVsUVZMS2FrZmdRSkM1TjhiNFppWTd2djFjLwpKeVppUldYQUs1TjdtR1FCNjhjQ0F3RUFBYU5aTUZj
d0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNS2hUK1hKRjhpcXp2a3p4Zzc1Q3FmdlVtSmNNQlVHQTFVZEVRUU8KTU
F5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS01LbEFvbGltZmorZFYycDdrUApxNkgxSFl4U3NoYUlrSUNxbFB6S2ZNRGc0bDVmZlNPQVBmVVY3
V3E0YkRsNXd1aXNWbk01Y0JJZXFlT1dGVXkrCmRuSUJPbzdXanZlb3R4cjlCSTdjNDlRK0pDNEhuU3RxeWwvcnhEeW1jcGxnSGpTc296TXRBSHNTaDZaTDlJaVQKM1FtQWNpdG
JEcFVtNnBWL2RUWDhqb3hGbEExWW5vMVNGazJyb1FZdXBoL20wMVFCa2FRT1QvRGZURVZ0dm5oNApncFU0aTB0Q2V0akpPM3FPQUg2VkZSVkowc2ZaREZ4aTBRdTdyQTVHNFIw
WGMyVWY0WVhmN1hxMjhSaGd5Qk1nCnAwcTBoelZmZUtXbjFZZ0VuNkRWTEYzQ2o5ZHJXUzB0RDdiTHBYRmZrMVliTy9nQnNyRDBRMnBUc2xlc2l0eG8KZ0N3PQotLS0tLUVORC
BDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://9220DC2A9C03753186E5231FCDE99754.gr7.us-east-2.eks.amazonaws.com
  name: EKSClustertest.us-east-2.eksctl.io
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0
VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1ETXdNakUxTWpRd00xb1hEVE16TURJeU56RTFNalF3TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pD
Q0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUh3CnFvS0hncWpCOHFvT3E0eEhCei9aS2pUc3lWUEx1ZnJKNUdKV0N2N1J6OXN0RDRlS1E2NUg3Kz
FwRnhPQ0QrblEKS2JxQnNYTlk4ZHNSWWhzQ1h0QU94czFtRUI3YkpnUGhOaExOeFc2YUFPdHJuVDZVbm1uZVJZaGljeEROTTJXTgo5WUFjWFV1bzZUYWhHYmlKeUJoKzJCbXJi
cWdFRG8rUVFvamQ2MXROdWMvbmdnZVdYUDlCQW5uZ2V4ZkkrR21nCjVMRCtlZ2doWXJuRjdGcjUwSUJ0Mno3blR4SFo1ZEtESmtDdlVDRDJVbTVIK0FvNFU0Ni9YVUdGYmNiYT
hNa3oKclM5dm1tcTY3WWhCS0dhVUdvZDdKcVBnd1dhYU9EeDdIRkp6blVsUVZMS2FrZmdRSkM1TjhiNFppWTd2djFjLwpKeVppUldYQUs1TjdtR1FCNjhjQ0F3RUFBYU5aTUZj
d0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNS2hUK1hKRjhpcXp2a3p4Zzc1Q3FmdlVtSmNNQlVHQTFVZEVRUU8KTU
F5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS01LbEFvbGltZmorZFYycDdrUApxNkgxSFl4U3NoYUlrSUNxbFB6S2ZNRGc0bDVmZlNPQVBmVVY3
V3E0YkRsNXd1aXNWbk01Y0JJZXFlT1dGVXkrCmRuSUJPbzdXanZlb3R4cjlCSTdjNDlRK0pDNEhuU3RxeWwvcnhEeW1jcGxnSGpTc296TXRBSHNTaDZaTDlJaVQKM1FtQWNpdG
JEcFVtNnBWL2RUWDhqb3hGbEExWW5vMVNGazJyb1FZdXBoL20wMVFCa2FRT1QvRGZURVZ0dm5oNApncFU0aTB0Q2V0akpPM3FPQUg2VkZSVkowc2ZaREZ4aTBRdTdyQTVHNFIw
WGMyVWY0WVhmN1hxMjhSaGd5Qk1nCnAwcTBoelZmZUtXbjFZZ0VuNkRWTEYzQ2o5ZHJXUzB0RDdiTHBYRmZrMVliTy9nQnNyRDBRMnBUc2xlc2l0eG8KZ0N3PQotLS0tLUVORC
BDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://9220DC2A9C03753186E5231FCDE99754.gr7.us-east-2.eks.amazonaws.com
  name: arn:aws:eks:us-east-2:591994479995:cluster/EKSClustertest
contexts:
- context:
    cluster: EKSClustertest.us-east-2.eksctl.io
    user: koko@EKSClustertest.us-east-2.eksctl.io
  name: koko@EKSClustertest.us-east-2.eksctl.io
- context:
    cluster: arn:aws:eks:us-east-2:591994479995:cluster/EKSClustertest
    user: arn:aws:eks:us-east-2:591994479995:cluster/EKSClustertest
  name: arn:aws:eks:us-east-2:591994479995:cluster/EKSClustertest
current-context: arn:aws:eks:us-east-2:591994479995:cluster/EKSClustertest
kind: Config
preferences: {}
users:
- name: koko@EKSClustertest.us-east-2.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --cluster-name
      - EKSClustertest
      - --region
      - us-east-2
      command: aws
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      provideClusterInfo: false
- name: arn:aws:eks:us-east-2:591994479995:cluster/EKSClustertest
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-2
      - eks
      - get-token
      - --cluster-name
      - EKSClustertest
      command: aws
      