apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondtask-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: secondtask
    spec:
      containers:
      - name: secondtask
        image: secondtask:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: secondtask-service
spec:
  selector:
    app: secondtask
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
  type: LoadBalancer
  externalIPs:
  - 192.168.65.3
